<?php

namespace Database\Seeders;

use App\Models\LoadoutChallenge;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class HntLoadoutChallengeSeeder extends Seeder
{
    public function run(): void
    {
        if (! Schema::hasTable('loadout_challenges')) {
            $this->command?->warn('Tabelle loadout_challenges existiert nicht. Bitte Patch 521/Migrationen zuerst installieren.');

            return;
        }

        $challenges = [
            [
                'title' => 'Romero-Ritus',
                'slug' => 'romero-ritus',
                'summary' => 'Ein alter Bayou-Klassiker: Romero rein, Nerven behalten, Bounty rausbringen.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDiese Challenge dreht sich um den klassischen Einzelschuss-Shotgun-Spielstil. Du gehst mit einer Romero 77 oder einer Romero-Variante in die Runde und spielst bewusst nah, geduldig und sauber. Gezählt wird eine Einreichung, wenn du einen erfolgreichen Extract mit mindestens einem Bounty Token oder einen klar dokumentierten Hunter-Kill mit anschließendem Extract nachweist.\n\nGedanke dahinter: Kein Spam, kein Dauerfeuer, sondern ein Schuss, ein Fenster, eine Entscheidung.",
                'rules' => "Erlaubt:\n- Romero 77 oder eine Romero-Variante als Hauptwaffe\n- Eine einfache Seitenwaffe nach Wahl\n- Tools und Heilung normal erlaubt\n\nNicht erlaubt:\n- Andere Shotguns als Hauptwaffe\n- Dolch-/Nitro-/Avtomat-ähnliche Luxus- oder Meme-Carry-Loadouts\n\nNachweis:\n- Screenshot vom Match-Ende oder kurzer Clip\n- Bounty-Extract oder sauber erkennbarer Hunter-Kill mit Extract",
                'loadout_notes' => "Empfohlen: Romero 77 + Caldwell Conversion / Pax, Medkit, Messer/Knuckle Knife, Chokes. Spezialmunition optional, aber nicht nötig.",
                'xp_reward' => 175,
                'is_featured' => true,
                'sort_order' => 10,
            ],
            [
                'title' => 'Free-Hunter-Schwur',
                'slug' => 'free-hunter-schwur',
                'summary' => 'Nimm einen kostenlosen Hunter und mach aus fast nichts einen echten Extract.',
                'description' => "Schwierigkeitsgrad: Leicht bis Mittel\n\nDu startest mit einem Free Hunter und spielst das Match möglichst nah an seinem ursprünglichen Loadout. Die Challenge soll zeigen, dass ein guter Run nicht vom teuersten Arsenal abhängt.\n\nGezählt wird ein erfolgreicher Extract. Bonuswürdig ist ein Extract mit Bounty, aber auch ein sauber gespielter Überlebensrun kann angenommen werden, wenn der Nachweis plausibel ist.",
                'rules' => "Erlaubt:\n- Free Hunter als Basis\n- Medkit darf ergänzt werden, falls keins vorhanden ist\n- Chokes dürfen ergänzt werden\n- Kleine Tool-Korrekturen sind erlaubt\n\nNicht erlaubt:\n- Hauptwaffen komplett gegen teure Meta-Waffen austauschen\n- Loadout nachträglich zu einem High-End-Build umbauen\n\nNachweis:\n- Screenshot vor oder nach dem Match, aus dem Free-Hunter-Charakter oder Match-Ergebnis plausibel hervorgeht",
                'loadout_notes' => "Der Kern ist nicht absolute Beweisbürokratie, sondern Fairness: Free Hunter nehmen, nicht künstlich aufrüsten, sauber spielen.",
                'xp_reward' => 125,
                'is_featured' => true,
                'sort_order' => 20,
            ],
            [
                'title' => 'Kein Long Ammo',
                'slug' => 'kein-long-ammo',
                'summary' => 'Keine Long-Ammo-Waffen. Gewinne mit Compact, Medium, Shotgun oder Special.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nLong Ammo bleibt zu Hause. Du spielst bewusst außerhalb der klassischen Long-Ammo-Komfortzone und musst Rotationen, Distanz und Timing sauberer lösen.\n\nDie Challenge zählt bei erfolgreichem Extract mit Bounty oder bei einem dokumentierten Fight mit anschließendem Extract.",
                'rules' => "Erlaubt:\n- Compact Ammo\n- Medium Ammo\n- Shotguns\n- Special Weapons wie Bow/Crossbow\n\nNicht erlaubt:\n- Long-Ammo-Hauptwaffen\n- Long-Ammo-Seitenwaffen\n\nNachweis:\n- Loadout-Screenshot plus Match-Ende oder kurzer Clip",
                'loadout_notes' => "Gute Kandidaten: Winfield/Frontier-Familie, Vetterli, Springfield, Caldwell Rival, Romero, Bow oder Crossbow. Namen können je nach Spielversion leicht variieren; entscheidend ist: keine Long Ammo.",
                'xp_reward' => 150,
                'is_featured' => true,
                'sort_order' => 30,
            ],
            [
                'title' => 'Pistolero',
                'slug' => 'pistolero',
                'summary' => 'Keine Rifles, keine Shotguns: Nur Pistolen und Revolver bringen dich nach Hause.',
                'description' => "Schwierigkeitsgrad: Schwer\n\nDu spielst die Runde nur mit Pistolen/Revolvern. Ob einzeln, dual oder mit Varianten, ist egal – Hauptsache, du verzichtest auf große Waffen und musst Distanz, Munition und Pushes bewusst wählen.\n\nEinreichungen zählen bei erfolgreichem Extract mit Bounty oder eindeutigem PvP-Erfolg plus Extract.",
                'rules' => "Erlaubt:\n- Pistolen und Revolver\n- Dual-Wield\n- Tools, Heilung und Chokes\n\nNicht erlaubt:\n- Rifles\n- Shotguns\n- Bows/Crossbows als Hauptschaden\n\nNachweis:\n- Loadout-Screenshot und Match-Ende oder kurzer Clip",
                'loadout_notes' => "Beispiele: Caldwell Conversion, Pax, Scottfield, Nagant, Bornheim. Uppercut nur erlauben, wenn du die Challenge bewusst härter/teurer zulassen willst.",
                'xp_reward' => 225,
                'is_featured' => false,
                'sort_order' => 40,
            ],
            [
                'title' => 'Bow im Bayou',
                'slug' => 'bow-im-bayou',
                'summary' => 'Leise, gefährlich, gnadenlos: Hunting Bow oder Crossbow als Kern des Runs.',
                'description' => "Schwierigkeitsgrad: Mittel bis Schwer\n\nDiese Challenge belohnt ruhiges Positioning, Geduld und saubere Abschlüsse. Du spielst Hunting Bow oder Crossbow als zentrale Waffe und versuchst, einen erfolgreichen Run zu liefern.\n\nGezählt wird ein Extract mit Bounty oder ein klar dokumentierter Hunter-Kill mit Bow/Crossbow und anschließendem Extract.",
                'rules' => "Erlaubt:\n- Hunting Bow oder Crossbow als Kernwaffe\n- Eine Seitenwaffe zur Absicherung\n- Tools und Heilung normal erlaubt\n\nNicht erlaubt:\n- Bow/Crossbow nur als Deko mitführen und den Run fast komplett mit Meta-Waffe spielen\n\nNachweis:\n- Clip oder Screenshot, der den Bow/Crossbow-Bezug plausibel zeigt",
                'loadout_notes' => "Stark für Spieler, die gern leise rotieren. Bonusidee für Admins: Extra erwähnen, wenn der Kill wirklich mit Pfeil/Bolzen erzielt wurde.",
                'xp_reward' => 200,
                'is_featured' => true,
                'sort_order' => 50,
            ],
            [
                'title' => 'Springfield-Predigt',
                'slug' => 'springfield-predigt',
                'summary' => 'Ein günstiges Single-Shot-Rifle, viel Geduld und ein sauberer Extract.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDie Springfield steht für einfache Mittel und gute Entscheidungen. Du spielst eine Springfield-Variante als Hauptwaffe und setzt auf Geduld, Kopftreffer und sauberes Nachsetzen.\n\nGezählt wird ein erfolgreicher Extract mit Bounty oder ein klarer PvP-Erfolg mit anschließendem Extract.",
                'rules' => "Erlaubt:\n- Springfield 1866 oder Variante\n- Seitenwaffe nach Wahl\n- Tools/Consumables normal\n\nNicht erlaubt:\n- Hauptwaffe während des Runs gegen Long-Ammo-Meta austauschen und damit die Challenge erfüllen\n\nNachweis:\n- Loadout-Screenshot plus Match-Ende oder Clip",
                'loadout_notes' => "Passt gut als Einsteiger-Challenge, weil sie günstig ist und trotzdem gutes Aim/Timing verlangt.",
                'xp_reward' => 150,
                'is_featured' => false,
                'sort_order' => 60,
            ],
            [
                'title' => 'Ein Schuss, ein Gebet',
                'slug' => 'ein-schuss-ein-gebet',
                'summary' => 'Nur Single-Shot-Waffen als Hauptwaffen. Jeder Fehler tut weh.',
                'description' => "Schwierigkeitsgrad: Schwer\n\nDiese Challenge ist für Spieler, die Druck aushalten. Deine Hauptwaffe muss nach jedem Schuss bewusst nachgeladen oder neu angesetzt werden. Keine schnellen Follow-up-Schüsse, kein Komfort.\n\nGezählt wird ein Bounty-Extract oder ein klar dokumentierter Fight mit anschließendem Extract.",
                'rules' => "Erlaubt:\n- Single-Shot-Rifles oder Single-Shot-Shotguns als Hauptwaffe\n- Seitenwaffe nach Wahl\n\nNicht erlaubt:\n- Repetierer, Levering-/Spam-Builds als Hauptlösung\n- Halbautomatische Komfortwaffen\n\nNachweis:\n- Loadout und Match-Ende dokumentieren",
                'loadout_notes' => "Beispiele: Sparks, Springfield, Martini-Henry, Romero. Je nach Balancing kannst du Seitenwaffen frei lassen oder ebenfalls einschränken.",
                'xp_reward' => 225,
                'is_featured' => false,
                'sort_order' => 70,
            ],
            [
                'title' => 'Shotgun-Beichte',
                'slug' => 'shotgun-beichte',
                'summary' => 'Nah ran, Risiko nehmen, Bounty sichern: Shotgun als klare Hauptwaffe.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDu spielst eine Shotgun als Hauptwaffe und musst dadurch aggressiver, mutiger und positionsbewusster spielen. Campen auf 120 Meter zählt nicht – diese Challenge soll echte Shotgun-Entscheidungen fördern.\n\nGezählt wird ein Extract mit Bounty oder ein PvP-Erfolg im Nahbereich mit anschließendem Extract.",
                'rules' => "Erlaubt:\n- Shotgun als Hauptwaffe\n- Seitenwaffe nach Wahl\n- Tools und Heilung normal\n\nNicht erlaubt:\n- Shotgun nur mitführen, aber den Run mit einer Fernkampfwaffe erledigen\n\nNachweis:\n- Clip besonders gern gesehen, Screenshot reicht bei Bounty-Extract",
                'loadout_notes' => "Romero, Caldwell Rival, Specter, Slate oder ähnliche Shotguns passen. Admin kann exotische Varianten zulassen.",
                'xp_reward' => 175,
                'is_featured' => false,
                'sort_order' => 80,
            ],
            [
                'title' => 'Messer zwischen den Zähnen',
                'slug' => 'messer-zwischen-den-zaehnen',
                'summary' => 'Melee muss eine echte Rolle spielen. Kein reiner Fernkampf-Run.',
                'description' => "Schwierigkeitsgrad: Schwer\n\nDiese Challenge verlangt, dass Melee nicht nur als Tool-Slot existiert, sondern aktiv zum Run beiträgt. Ziel ist ein Extract, bei dem mindestens ein relevanter Melee-Einsatz dokumentiert ist – gegen Boss, Meathead, Immolator mit passendem Tool oder im Idealfall gegen einen Hunter.\n\nPvP-Melee ist Bonus, aber nicht zwingend Pflicht, damit die Challenge fair bleibt.",
                'rules' => "Erlaubt:\n- Eine normale Waffe plus Melee-Fokus\n- Combat Axe, Machete, Saber, Baseball Bat oder starke Melee-Tools, je nach Verfügbarkeit\n\nNicht erlaubt:\n- Melee nur mitnehmen und nie nutzen\n\nNachweis:\n- Kurzer Clip ist hier klar besser als nur Screenshot",
                'loadout_notes' => "Diese Challenge eignet sich gut als Clip-Generator für Moments. Nicht zu streng machen, sonst reichen zu wenige Nutzer ein.",
                'xp_reward' => 250,
                'is_featured' => false,
                'sort_order' => 90,
            ],
            [
                'title' => 'Leiser Vertrag',
                'slug' => 'leiser-vertrag',
                'summary' => 'Silent Loadout: Leise Waffen, kontrollierte Rotationen, möglichst wenig Lärm.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDu spielst einen möglichst leisen Run. Silencer, Bow, Crossbow und vorsichtiges Pathing stehen im Mittelpunkt. Die Challenge ist nicht als unmögliche No-Sound-Regel gedacht, sondern als Stealth-Spielstil.\n\nGezählt wird ein erfolgreicher Extract, besonders stark mit Bounty oder einem leise erzielten Hunter-Kill.",
                'rules' => "Erlaubt:\n- Silenced Weapons\n- Bow/Crossbow\n- Leise Tools\n- Normale Heilung\n\nNicht erlaubt:\n- Lauter Meta-Run, bei dem Silent-Waffe nur mitgenommen wird\n\nNachweis:\n- Loadout-Screenshot und Match-Ergebnis; Clip optional",
                'loadout_notes' => "Gut für Solo-Spieler. Admin kann als Zusatzwertung 'ohne laute Schüsse' markieren, aber für v1 nicht zwingend prüfen.",
                'xp_reward' => 175,
                'is_featured' => false,
                'sort_order' => 100,
            ],
            [
                'title' => 'Budget-Blutpakt',
                'slug' => 'budget-blutpakt',
                'summary' => 'Günstig rein, lebend raus. Kein Luxus-Loadout, kein Meta-Geldverbrennen.',
                'description' => "Schwierigkeitsgrad: Leicht bis Mittel\n\nDiese Challenge ist für sparsame Hunter. Du nutzt ein bewusst günstiges Loadout und versuchst trotzdem, ein verwertbares Ergebnis zu erzielen. Da Preise sich ändern können, gilt kein harter Dollar-Wert, sondern die Admin-Regel: sichtbar günstige Waffen, kein High-End-Arsenal.\n\nGezählt wird ein erfolgreicher Extract, idealerweise mit Bounty.",
                'rules' => "Erlaubt:\n- Günstige Basiswaffen\n- Einfache Seitenwaffen\n- Normale Tools/Heilung\n\nNicht erlaubt:\n- Nitro, Dolch, Avtomat-ähnliche Luxus-Builds\n- Teure Meta-Kombinationen, die die Idee aushebeln\n\nNachweis:\n- Loadout-Screenshot vor dem Match plus Ergebnis",
                'loadout_notes' => "Absichtlich ohne festen Preiswert, weil Hunt-Preise/Balancing sich ändern können. Im Admintext bei Bedarf später eine konkrete Grenze ergänzen.",
                'xp_reward' => 125,
                'is_featured' => true,
                'sort_order' => 110,
            ],
            [
                'title' => 'Kein Feuer aus der Tasche',
                'slug' => 'kein-feuer-aus-der-tasche',
                'summary' => 'Keine einfachen Burn-Tools: Wenn Feuer, dann bewusst über Weltobjekte oder klare Consumables.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDiese Challenge nimmt dir den bequemen Burn-Komfort. Du verzichtest auf schnelle Tool-/Waffen-Burns und musst Downs, Druck und Rotationen anders lösen.\n\nGezählt wird ein erfolgreicher Extract oder ein Fight, bei dem du ohne billige Burn-Abkürzung überlebst.",
                'rules' => "Erlaubt:\n- Normale Waffen\n- Heilung, Chokes, Utility\n- Weltlaternen oder bewusst eingesetzte Fire Bombs, wenn Admin das zulässt\n\nNicht erlaubt:\n- Loadout bewusst um schnelle Burn-Tools/Waffen herum bauen\n\nNachweis:\n- Match-Ende reicht, bei Streitfällen Clip bevorzugt",
                'loadout_notes' => "Diese Challenge ist eher Verhaltensregel als Loadout-Liste. Gut geeignet, wenn die Community über Burn-Meta diskutiert.",
                'xp_reward' => 150,
                'is_featured' => false,
                'sort_order' => 120,
            ],
            [
                'title' => 'Vetterli-Waldläufer',
                'slug' => 'vetterli-waldlaeufer',
                'summary' => 'Solides Medium-Ammo-Spiel: Vetterli als ehrlicher Allrounder.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDu spielst eine Vetterli-Variante als Hauptwaffe und versuchst, mit sauberer Distanzkontrolle und ruhigen Nachschüssen zu arbeiten. Kein High-End-Carry, keine Ausrede – nur solides Rifle-Gameplay.\n\nGezählt wird ein Bounty-Extract oder PvP-Erfolg plus Extract.",
                'rules' => "Erlaubt:\n- Vetterli oder Vetterli-Variante als Hauptwaffe\n- Seitenwaffe frei\n- Tools/Consumables normal\n\nNicht erlaubt:\n- Hauptwaffe im Match ersetzen und Challenge trotzdem claimen\n\nNachweis:\n- Loadout-Screenshot und Ergebnis",
                'loadout_notes' => "Gute Standard-Challenge für Spieler, die nicht komplett aus ihrer Komfortzone sollen.",
                'xp_reward' => 150,
                'is_featured' => false,
                'sort_order' => 130,
            ],
            [
                'title' => 'Nagant-Nachtwache',
                'slug' => 'nagant-nachtwache',
                'summary' => 'Nagant-Familie im Fokus: schlicht, günstig, unangenehm ehrlich.',
                'description' => "Schwierigkeitsgrad: Mittel bis Schwer\n\nDiese Challenge nutzt die Nagant-Familie als Kern. Du kannst mit einer Nagant-Variante, dual oder als Seitenwaffe spielen – wichtig ist, dass der Run sichtbar um einfache Pistolenarbeit gebaut ist.\n\nGezählt wird ein Extract mit Bounty oder ein klarer Fight-Erfolg plus Extract.",
                'rules' => "Erlaubt:\n- Nagant-Varianten\n- Dual Nagant\n- Eine einfache Hauptwaffe, wenn Nagant aktiv genutzt wird\n\nNicht erlaubt:\n- Nagant nur als Deko neben einem kompletten Meta-Build\n\nNachweis:\n- Loadout-Screenshot, Clip bei PvP empfohlen",
                'loadout_notes' => "Optional härter: Nur Nagant/dual Nagant erlauben. Für v1 lieber moderat lassen.",
                'xp_reward' => 175,
                'is_featured' => false,
                'sort_order' => 140,
            ],
            [
                'title' => 'Bossjäger ohne Komfort',
                'slug' => 'bossjaeger-ohne-komfort',
                'summary' => 'Boss finden, Boss legen, Bounty extrahieren – aber ohne High-End-Loadout.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDer Fokus liegt auf dem Hunt-Kern: Boss finden, banishen, Bounty rausbringen. Das Loadout soll solide, aber nicht luxuriös sein. Diese Challenge eignet sich gut für Solo, Duo und Trio.\n\nGezählt wird nur ein Extract mit mindestens einem Bounty Token.",
                'rules' => "Erlaubt:\n- Solide normale Waffen\n- Tools/Heilung normal\n\nNicht erlaubt:\n- Reiner PvP-Run ohne Bounty\n- Luxus-Loadout, wenn die Challenge als Budget-/Objective-Run gedacht ist\n\nNachweis:\n- Match-Ende mit Bounty Token klar sichtbar",
                'loadout_notes' => "Sehr gut als wöchentliche Standard-Challenge, weil sie objektives Spielen belohnt.",
                'xp_reward' => 175,
                'is_featured' => true,
                'sort_order' => 150,
            ],
            [
                'title' => 'Solo gegen den Sumpf',
                'slug' => 'solo-gegen-den-sumpf',
                'summary' => 'Solo rein, Solo raus. Kein Team, keine Ausreden.',
                'description' => "Schwierigkeitsgrad: Schwer\n\nDiese Challenge ist für Solo-Spieler. Das Loadout ist frei, aber der Run muss solo gespielt werden. Ziel ist ein Extract, idealerweise mit Bounty oder mindestens einem klar dokumentierten PvP-Erfolg.\n\nDa Solo-Runs je nach MMR extrem unterschiedlich ausfallen, sollte der Admin bei der Prüfung fair bleiben.",
                'rules' => "Erlaubt:\n- Loadout frei\n- Solo-only\n\nNicht erlaubt:\n- Duo/Trio-Run als Solo-Challenge einreichen\n\nNachweis:\n- Match-Ende oder Clip, aus dem Solo-Run plausibel wird",
                'loadout_notes' => "Nicht zu oft aktivieren, sonst frustriert es Casual-Spieler. Als Wochen-Challenge aber stark.",
                'xp_reward' => 250,
                'is_featured' => false,
                'sort_order' => 160,
            ],
            [
                'title' => 'Kein Scope, kein Problem',
                'slug' => 'kein-scope-kein-problem',
                'summary' => 'Keine Scopes. Iron Sights, Positioning und Nerven entscheiden.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDu verzichtest auf Marksman-, Deadeye-, Sniper- und ähnliche Scope-Varianten. Der Run soll näher, direkter und weniger passiv werden.\n\nGezählt wird ein Bounty-Extract oder ein Fight-Erfolg plus Extract.",
                'rules' => "Erlaubt:\n- Iron-Sight-Waffen\n- Shotguns\n- Bow/Crossbow\n- Seitenwaffen ohne Scope\n\nNicht erlaubt:\n- Scope-Varianten als Hauptwaffe\n\nNachweis:\n- Loadout-Screenshot und Match-Ende",
                'loadout_notes' => "Guter Kontrast zu Sniper-Spielstilen, ohne Spieler auf eine bestimmte Waffe festzunageln.",
                'xp_reward' => 150,
                'is_featured' => false,
                'sort_order' => 170,
            ],
            [
                'title' => 'Kontraband-Kodex',
                'slug' => 'kontraband-kodex',
                'summary' => 'Spiele mit gefundenem oder geerbtem Kram statt sauber gekauftem Wunschloadout.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDiese Challenge ist für improvisierte Runs. Nutze Contraband, Loot aus vorherigen Runden oder ein bewusst zusammengewürfeltes Loadout. Es geht nicht um perfekte Meta, sondern um Bayou-Improvisation.\n\nGezählt wird ein Extract, besser mit Bounty oder dokumentiertem PvP-Erfolg.",
                'rules' => "Erlaubt:\n- Contraband-Waffen\n- Zusammengewürfelte Loadouts\n- Free-Hunter-Basis\n\nNicht erlaubt:\n- Perfekt gekaufter Meta-Build und dann 'Contraband' behaupten\n\nNachweis:\n- Loadout-Screenshot vor dem Match empfohlen",
                'loadout_notes' => "Schöne Casual-Challenge. Nicht zu streng beweisen, sonst wird sie nervig.",
                'xp_reward' => 125,
                'is_featured' => false,
                'sort_order' => 180,
            ],
            [
                'title' => 'Bounty oder nichts',
                'slug' => 'bounty-oder-nichts',
                'summary' => 'Kills zählen nicht. Nur ein Extract mit Bounty erfüllt den Vertrag.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDiese Challenge richtet den Fokus komplett auf das Objective. Egal wie viele Fights du hattest: Ohne Bounty-Extract zählt der Run nicht.\n\nDas Loadout ist frei, aber wer nur PvP farmt und nicht extrahiert, erfüllt die Challenge nicht.",
                'rules' => "Erlaubt:\n- Loadout frei\n- Solo, Duo oder Trio\n\nNicht erlaubt:\n- Reine Kill-Runden ohne Bounty-Extract\n\nNachweis:\n- Match-Ende mit Bounty Token klar sichtbar",
                'loadout_notes' => "Perfekt, wenn du objective-basiertes Spielen fördern willst. Auch gut mit Cups kombinierbar.",
                'xp_reward' => 175,
                'is_featured' => true,
                'sort_order' => 190,
            ],
            [
                'title' => 'Clutch oder Untergang',
                'slug' => 'clutch-oder-untergang',
                'summary' => 'Ein starker Moment zählt: 1v2, 1v3, Rettung, Revive oder letzter Extract.',
                'description' => "Schwierigkeitsgrad: Offen\n\nDiese Challenge ist bewusst clip-orientiert. Es geht nicht um eine bestimmte Waffe, sondern um einen starken Hunt-Moment: Clutch, Rettung, riskanter Revive, Last-Second-Extract oder ein Fight, der die Runde gedreht hat.\n\nGezählt wird bevorzugt mit kurzem Clip oder Moment-Einreichung.",
                'rules' => "Erlaubt:\n- Loadout frei\n- Clip oder Moment bevorzugt\n\nNicht erlaubt:\n- Normale, unspektakuläre Extracts ohne erkennbaren Challenge-Moment\n\nNachweis:\n- Kurzer Clip/Moment stark empfohlen",
                'loadout_notes' => "Diese Challenge verbindet Loadout-Challenges mit Moments. Gut für Community-Content und Social Posts.",
                'xp_reward' => 200,
                'is_featured' => false,
                'sort_order' => 200,
            ],
            [
                'title' => 'Rivalenvertrag',
                'slug' => 'rivalenvertrag',
                'summary' => 'Caldwell Rival oder andere Double-Barrel-Action: schnell rein, schnell entscheiden.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDu spielst eine Double-Barrel-Shotgun wie die Caldwell Rival als Hauptwaffe. Der Spielstil ist riskant: zwei starke Chancen, dann wird es unangenehm.\n\nGezählt wird ein Extract mit Bounty oder ein klarer Nahkampf-PvP-Erfolg plus Extract.",
                'rules' => "Erlaubt:\n- Caldwell Rival oder vergleichbare Double-Barrel-Shotgun\n- Seitenwaffe frei\n\nNicht erlaubt:\n- Shotgun nur als Backup, Hauptarbeit mit Fernkampf-Meta\n\nNachweis:\n- Loadout-Screenshot und Ergebnis; Clip bei PvP empfohlen",
                'loadout_notes' => "Gute Alternative zum Romero-Ritus, weil sie aggressiver und schneller ist.",
                'xp_reward' => 175,
                'is_featured' => false,
                'sort_order' => 210,
            ],
            [
                'title' => 'Kein Luxus im Bayou',
                'slug' => 'kein-luxus-im-bayou',
                'summary' => 'Keine Prestige-Meta. Keine teuren Komfortwaffen. Gewinne mit ehrlichem Zeug.',
                'description' => "Schwierigkeitsgrad: Mittel\n\nDiese Challenge blockt bewusst die ganz teuren Komfortlösungen. Der genaue Bann kann je nach Balance angepasst werden, aber die Idee bleibt: kein Luxus-Carry, sondern solide Mittelklasse oder günstiger.\n\nGezählt wird ein Bounty-Extract oder Fight-Erfolg plus Extract.",
                'rules' => "Nicht erlaubt, sofern Admin nicht anders entscheidet:\n- Nitro\n- Dolch\n- Avtomat-ähnliche Luxus-/Spam-Builds\n- Extrem teure Meta-Kombinationen\n\nErlaubt:\n- Solide Budget-/Mittelklasse-Waffen\n- Normale Tools und Heilung\n\nNachweis:\n- Loadout-Screenshot plus Ergebnis",
                'loadout_notes' => "Diese Challenge ist absichtlich flexibel, weil Balance und Preise sich ändern können. Der Admin kann vor Aktivierung konkrete Bannlisten ergänzen.",
                'xp_reward' => 175,
                'is_featured' => false,
                'sort_order' => 220,
            ],
            [
                'title' => 'Extraktion bei Nacht',
                'slug' => 'extraktion-bei-nacht',
                'summary' => 'Dunkle Runde, ruhiger Puls: Extract schaffen, egal wie dreckig der Weg war.',
                'description' => "Schwierigkeitsgrad: Situativ\n\nWenn du eine Nacht-, Nebel- oder besonders schlechte Sicht-Runde erwischst, zählt diese Challenge. Das Loadout ist frei, aber Ziel ist ein sauberer Extract, idealerweise mit Bounty.\n\nDa Wetter und Tageszeit nicht immer steuerbar sind, ist die Challenge gut als länger laufende Aufgabe geeignet.",
                'rules' => "Erlaubt:\n- Loadout frei\n- Solo, Duo oder Trio\n\nBedingung:\n- Sichtbar dunkle/schlechte Sichtbedingungen oder Admin erkennt die Runde als passend an\n\nNachweis:\n- Screenshot oder Clip, Match-Ende bevorzugt",
                'loadout_notes' => "Nicht als Tageschallenge verwenden, sondern eher als Wochen-/Saisonaufgabe, weil Spieler die Bedingung nicht komplett kontrollieren.",
                'xp_reward' => 150,
                'is_featured' => false,
                'sort_order' => 230,
            ],
            [
                'title' => 'Moment-Macher',
                'slug' => 'moment-macher',
                'summary' => 'Reiche keinen Screenshot ein, sondern einen echten Clip oder Moment zur Challenge.',
                'description' => "Schwierigkeitsgrad: Offen\n\nDiese Challenge soll HNT-Moments füttern. Das Loadout kann vom Admin frei vorgegeben oder offen gelassen werden. Wichtig ist: Die Einreichung soll als Clip/Moment funktionieren und nicht nur als Endscreen.\n\nGezählt wird ein kurzer Clip, der einen klaren Hunt-Moment zeigt.",
                'rules' => "Erlaubt:\n- Loadout frei oder nach Wochenvorgabe\n- Clip/Moment als Nachweis\n\nNicht erlaubt:\n- Nur leerer Ergebnis-Screenshot ohne erkennbaren Moment\n\nNachweis:\n- Kurzer Clip oder HNT-Moment",
                'loadout_notes' => "Ideal, um Loadout-Challenges, Moment der Woche und Profil-Vitrine miteinander zu verbinden.",
                'xp_reward' => 200,
                'is_featured' => true,
                'sort_order' => 240,
            ],
        ];

        foreach ($challenges as $challenge) {
            LoadoutChallenge::updateOrCreate(
                ['slug' => $challenge['slug']],
                [
                    'created_by' => null,
                    'title' => $challenge['title'],
                    'summary' => $challenge['summary'],
                    'description' => $challenge['description'],
                    'rules' => $challenge['rules'],
                    'loadout_notes' => $challenge['loadout_notes'],
                    'status' => LoadoutChallenge::STATUS_ACTIVE,
                    'starts_at' => null,
                    'ends_at' => null,
                    'xp_reward' => $challenge['xp_reward'],
                    'badge_slug' => null,
                    'is_featured' => $challenge['is_featured'],
                    'sort_order' => $challenge['sort_order'],
                ]
            );
        }
    }
}
