<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (! Schema::hasTable('crown_shop_items')) {
            return;
        }

        $now = now();
        $items = [
            [
                'key' => 'avatar_frame_bone_hunter',
                'type' => 'avatar_frame',
                'slot' => 'avatar_frame',
                'name_de' => 'Bone-Hunter Avatarrahmen',
                'name_en' => 'Bone Hunter Avatar Frame',
                'description_de' => 'Ein bleicher Knochenrahmen für Jäger, die im Bayou nicht mehr sauber rauskommen.',
                'description_en' => 'A pale bone frame for hunters who never leave the bayou clean.',
                'price' => 220,
                'rarity' => 'rare',
                'icon' => 'skull',
                'preview_class' => 'bone-hunter',
                'sort_order' => 21,
            ],
            [
                'key' => 'avatar_frame_swamp_relic',
                'type' => 'avatar_frame',
                'slot' => 'avatar_frame',
                'name_de' => 'Swamp-Relic Avatarrahmen',
                'name_en' => 'Swamp Relic Avatar Frame',
                'description_de' => 'Moos, altes Metall und dunkle Sumpfglut als dezenter Profilrahmen.',
                'description_en' => 'Moss, old metal and swamp embers as a subtle profile frame.',
                'price' => 280,
                'rarity' => 'rare',
                'icon' => 'shield',
                'preview_class' => 'swamp-relic',
                'sort_order' => 22,
            ],
            [
                'key' => 'avatar_frame_gilded_bounty',
                'type' => 'avatar_frame',
                'slot' => 'avatar_frame',
                'name_de' => 'Gilded-Bounty Avatarrahmen',
                'name_en' => 'Gilded Bounty Avatar Frame',
                'description_de' => 'Ein schwerer Goldrahmen für Spieler, die auffallen wollen.',
                'description_en' => 'A heavy gold frame for players who want to stand out.',
                'price' => 700,
                'rarity' => 'legendary',
                'icon' => 'crown',
                'preview_class' => 'gilded-bounty',
                'sort_order' => 23,
            ],
            [
                'key' => 'avatar_frame_black_ritual',
                'type' => 'avatar_frame',
                'slot' => 'avatar_frame',
                'name_de' => 'Black-Ritual Avatarrahmen',
                'name_en' => 'Black Ritual Avatar Frame',
                'description_de' => 'Ein dunkler Ritualrahmen mit rotem Flackern. Kosmetisch, ohne Vorteil.',
                'description_en' => 'A dark ritual frame with red flicker. Cosmetic, with no advantage.',
                'price' => 900,
                'rarity' => 'event',
                'icon' => 'seal-warning',
                'preview_class' => 'black-ritual',
                'is_limited' => true,
                'sort_order' => 24,
            ],
            [
                'key' => 'username_glow_soulfire',
                'type' => 'username_effect',
                'slot' => 'username_effect',
                'name_de' => 'Soulfire Username Glow',
                'name_en' => 'Soulfire Username Glow',
                'description_de' => 'Ein kalter, geisterhafter Glut-Effekt für deinen Namen.',
                'description_en' => 'A cold ghostly ember glow for your name.',
                'price' => 300,
                'rarity' => 'rare',
                'icon' => 'flame',
                'preview_class' => 'soulfire',
                'sort_order' => 51,
            ],
            [
                'key' => 'username_effect_bounty_gold',
                'type' => 'username_effect',
                'slot' => 'username_effect',
                'name_de' => 'Bounty-Gold Username',
                'name_en' => 'Bounty Gold Username',
                'description_de' => 'Ein goldener Namenseffekt mit Bounty-Schimmer.',
                'description_en' => 'A golden name effect with bounty shimmer.',
                'price' => 480,
                'rarity' => 'epic',
                'icon' => 'coins',
                'preview_class' => 'bounty-gold',
                'sort_order' => 52,
            ],
            [
                'key' => 'username_effect_moonlit',
                'type' => 'username_effect',
                'slot' => 'username_effect',
                'name_de' => 'Moonlit Username',
                'name_en' => 'Moonlit Username',
                'description_de' => 'Ein kühler Mondschein-Effekt für einen ruhigeren Look.',
                'description_en' => 'A cool moonlit effect for a calmer look.',
                'price' => 260,
                'rarity' => 'rare',
                'icon' => 'moon',
                'preview_class' => 'moonlit',
                'sort_order' => 53,
            ],
            [
                'key' => 'username_effect_cursed_red',
                'type' => 'username_effect',
                'slot' => 'username_effect',
                'name_de' => 'Cursed-Red Username',
                'name_en' => 'Cursed Red Username',
                'description_de' => 'Ein aggressiver roter Namenseffekt für den düsteren Auftritt.',
                'description_en' => 'An aggressive red name effect for a darker presence.',
                'price' => 750,
                'rarity' => 'legendary',
                'icon' => 'drop',
                'preview_class' => 'cursed-red',
                'sort_order' => 54,
            ],
            [
                'key' => 'profile_banner_swamp_fog',
                'type' => 'profile_banner',
                'slot' => 'profile_banner',
                'name_de' => 'Swamp-Fog Profilbanner',
                'name_en' => 'Swamp Fog Profile Banner',
                'description_de' => 'Ein nebliger Sumpf-Overlay für deinen Profilkopf.',
                'description_en' => 'A foggy swamp overlay for your profile header.',
                'price' => 350,
                'rarity' => 'rare',
                'icon' => 'cloud-fog',
                'preview_class' => 'swamp-fog',
                'sort_order' => 31,
            ],
            [
                'key' => 'profile_banner_blood_moon',
                'type' => 'profile_banner',
                'slot' => 'profile_banner',
                'name_de' => 'Blood-Moon Profilbanner',
                'name_en' => 'Blood Moon Profile Banner',
                'description_de' => 'Dunkler Rotmond-Look für deinen Profilheader.',
                'description_en' => 'A dark blood-moon look for your profile header.',
                'price' => 650,
                'rarity' => 'epic',
                'icon' => 'moon-stars',
                'preview_class' => 'blood-moon',
                'sort_order' => 32,
            ],
            [
                'key' => 'profile_banner_ritual_mark',
                'type' => 'profile_banner',
                'slot' => 'profile_banner',
                'name_de' => 'Ritual-Mark Profilbanner',
                'name_en' => 'Ritual Mark Profile Banner',
                'description_de' => 'Ein okkulter Banner-Effekt mit roter Markierung und dunklem Vignette-Look.',
                'description_en' => 'An occult banner effect with red markings and a dark vignette look.',
                'price' => 900,
                'rarity' => 'legendary',
                'icon' => 'pentagram',
                'preview_class' => 'ritual-mark',
                'sort_order' => 33,
            ],
            [
                'key' => 'title_swampborn',
                'type' => 'title',
                'slot' => 'profile_title',
                'name_de' => 'Titel: Swampborn',
                'name_en' => 'Title: Swampborn',
                'description_de' => 'Kosmetischer Profil-Titel für echte Bayou-Stammgäste.',
                'description_en' => 'A cosmetic profile title for true bayou regulars.',
                'price' => 140,
                'rarity' => 'common',
                'icon' => 'tag',
                'preview_class' => 'title-swampborn',
                'sort_order' => 71,
            ],
            [
                'key' => 'title_solo_extractor',
                'type' => 'title',
                'slot' => 'profile_title',
                'name_de' => 'Titel: Solo Extractor',
                'name_en' => 'Title: Solo Extractor',
                'description_de' => 'Kosmetischer Titel für Solo-Spieler mit Nerven aus Stahl.',
                'description_en' => 'A cosmetic title for solo players with nerves of steel.',
                'price' => 220,
                'rarity' => 'rare',
                'icon' => 'person-simple-run',
                'preview_class' => 'title-solo-extractor',
                'sort_order' => 72,
            ],
            [
                'key' => 'title_bounty_claimed',
                'type' => 'title',
                'slot' => 'profile_title',
                'name_de' => 'Titel: Bounty Claimed',
                'name_en' => 'Title: Bounty Claimed',
                'description_de' => 'Kosmetischer Titel für Spieler, die mit Beute nach Hause gehen.',
                'description_en' => 'A cosmetic title for players who make it home with the prize.',
                'price' => 260,
                'rarity' => 'rare',
                'icon' => 'crosshair',
                'preview_class' => 'title-bounty-claimed',
                'sort_order' => 73,
            ],
            [
                'key' => 'title_clutch_survivor',
                'type' => 'title',
                'slot' => 'profile_title',
                'name_de' => 'Titel: Clutch Survivor',
                'name_en' => 'Title: Clutch Survivor',
                'description_de' => 'Kosmetischer Titel für knappe Runden und dreckige Extraktionen.',
                'description_en' => 'A cosmetic title for tight rounds and dirty extracts.',
                'price' => 420,
                'rarity' => 'epic',
                'icon' => 'medal',
                'preview_class' => 'title-clutch-survivor',
                'sort_order' => 74,
            ],
            [
                'key' => 'title_the_banisher',
                'type' => 'title',
                'slot' => 'profile_title',
                'name_de' => 'Titel: The Banisher',
                'name_en' => 'Title: The Banisher',
                'description_de' => 'Legendärer kosmetischer Titel für den großen Auftritt.',
                'description_en' => 'A legendary cosmetic title for a stronger presence.',
                'price' => 800,
                'rarity' => 'legendary',
                'icon' => 'trophy',
                'preview_class' => 'title-the-banisher',
                'sort_order' => 75,
            ],
        ];

        foreach ($items as $item) {
            $existing = DB::table('crown_shop_items')->where('key', $item['key'])->exists();
            DB::table('crown_shop_items')->updateOrInsert(
                ['key' => $item['key']],
                array_merge($item, [
                    'is_active' => $item['is_active'] ?? true,
                    'is_limited' => $item['is_limited'] ?? false,
                    'available_from' => $item['available_from'] ?? null,
                    'available_until' => $item['available_until'] ?? null,
                    'metadata' => $item['metadata'] ?? null,
                    'created_at' => $existing ? DB::table('crown_shop_items')->where('key', $item['key'])->value('created_at') : $now,
                    'updated_at' => $now,
                ])
            );
        }
    }

    public function down(): void
    {
        if (! Schema::hasTable('crown_shop_items')) {
            return;
        }

        DB::table('crown_shop_items')->whereIn('key', [
            'avatar_frame_bone_hunter',
            'avatar_frame_swamp_relic',
            'avatar_frame_gilded_bounty',
            'avatar_frame_black_ritual',
            'username_glow_soulfire',
            'username_effect_bounty_gold',
            'username_effect_moonlit',
            'username_effect_cursed_red',
            'profile_banner_swamp_fog',
            'profile_banner_blood_moon',
            'profile_banner_ritual_mark',
            'title_swampborn',
            'title_solo_extractor',
            'title_bounty_claimed',
            'title_clutch_survivor',
            'title_the_banisher',
        ])->delete();
    }
};
