<?php

return [
    'phase' => '22',
    'source' => 'HTML Template.zip / Vikinger HTML Template',
    'principles' => [
        'Vikinger HTML-Dateien sind visuelle und strukturelle Referenz, nicht Daten- oder Funktionsquelle.',
        'Marketplace- und Store-Bereiche werden nicht als hnt.rocks-Funktion übernommen.',
        'Groups werden fachlich als Teams interpretiert.',
        'Design-Umbau erfolgt modulweise: Shell zuerst, danach Feed, Profil, Teams/LFG und Spezialmodule.',
        'Bestehende Laravel-Controller, Models und Migrationen bleiben funktionale Wahrheit.',
    ],
    'modules' => [
        [
            'area' => 'Shell / Globales Layout',
            'route' => 'Alle eingeloggten Seiten',
            'template_files' => ['newsfeed.html', 'overview.html'],
            'target_views' => ['resources/views/layouts/app.blade.php', 'resources/views/partials/head.blade.php', 'resources/views/partials/header.blade.php', 'resources/views/partials/sidebar.blade.php', 'resources/views/partials/footer.blade.php'],
            'status' => 'nächster Design-Schritt',
            'notes' => 'Header, Sidebar, content-grid, Floating-Header-Struktur und mobile Pattern zuerst angleichen.',
        ],
        [
            'area' => 'Newsfeed / Wall',
            'route' => '/feed',
            'template_files' => ['newsfeed.html'],
            'target_views' => ['resources/views/feed/index.blade.php', 'resources/views/feed/partials/post-card.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Composer, Post Cards, Kommentare, Reactions und rechte Widgets aus Vikinger ableiten.',
        ],
        [
            'area' => 'Profil',
            'route' => '/profile und /u/{username}',
            'template_files' => ['profile-timeline.html', 'profile-about.html', 'profile-friends.html', 'profile-photos.html', 'profile-videos.html', 'profile-badges.html'],
            'target_views' => ['resources/views/profile/show.blade.php', 'resources/views/profile/edit.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Profile Header, Stats, Badges, Timeline und About-Karten sauber übernehmen.',
        ],
        [
            'area' => 'Mitglieder / Spieler finden',
            'route' => '/members',
            'template_files' => ['members.html'],
            'target_views' => ['resources/views/members/index.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Member Cards und Filterleiste aus members.html ableiten.',
        ],
        [
            'area' => 'Teams statt Gruppen',
            'route' => '/teams',
            'template_files' => ['groups.html', 'group-timeline.html', 'group-info.html', 'group-members.html', 'group-events.html', 'hub-group-management.html', 'hub-group-invitations.html'],
            'target_views' => ['resources/views/teams/index.blade.php', 'resources/views/teams/show.blade.php', 'resources/views/teams/create.blade.php', 'resources/views/teams/edit.blade.php', 'resources/views/teams/partials/team-card.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Alle sichtbaren Begriffe bleiben hnt.rocks-seitig Teams, nicht Groups.',
        ],
        [
            'area' => 'LFG / Mitspielersuche',
            'route' => '/lfg',
            'template_files' => ['members.html', 'groups.html', 'newsfeed.html'],
            'target_views' => ['resources/views/lfg/index.blade.php', 'resources/views/lfg/show.blade.php', 'resources/views/lfg/create.blade.php', 'resources/views/lfg/edit.blade.php', 'resources/views/lfg/partials/lfg-card.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Kein direktes Template-Pendant; Karten/Filter aus Members/Groups und Social Cards kombinieren.',
        ],
        [
            'area' => 'Team-LFG',
            'route' => '/team-lfg',
            'template_files' => ['groups.html', 'group-members.html', 'hub-group-management.html'],
            'target_views' => ['resources/views/team-lfg/index.blade.php', 'resources/views/team-lfg/show.blade.php', 'resources/views/team-lfg/create.blade.php', 'resources/views/team-lfg/edit.blade.php', 'resources/views/team-lfg/partials/team-lfg-card.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Recruiting als Team-nahe Card-Struktur aus Gruppen/Member-Pattern ableiten.',
        ],
        [
            'area' => 'Nachrichten',
            'route' => '/messages',
            'template_files' => ['hub-profile-messages.html'],
            'target_views' => ['resources/views/messages/index.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Hub-Messages-Struktur als Vorlage für Inbox und Chatbereich nutzen.',
        ],
        [
            'area' => 'Benachrichtigungen',
            'route' => '/notifications',
            'template_files' => ['hub-profile-notifications.html'],
            'target_views' => ['resources/views/notifications/index.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Notification-Liste und Filter aus Hub-Template übernehmen.',
        ],
        [
            'area' => 'Mediathek',
            'route' => '/media',
            'template_files' => ['profile-photos.html', 'profile-photos-inside.html', 'profile-videos.html'],
            'target_views' => ['resources/views/media/index.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Galerie- und Video-Karten aus Profil-Media-Seiten ableiten.',
        ],
        [
            'area' => 'Moments / Reels',
            'route' => '/moments',
            'template_files' => ['profile-videos.html', 'streams.html'],
            'target_views' => ['resources/views/moments/index.blade.php', 'resources/views/moments/show.blade.php', 'resources/views/moments/create.blade.php'],
            'status' => 'funktional vorhanden, TikTok-Design später separat',
            'notes' => 'Vikinger liefert Medien-/Video-Basis, der echte Reels-Viewer bleibt eine eigene hnt.rocks-Komponente.',
        ],
        [
            'area' => 'Cups / Events',
            'route' => '/cups',
            'template_files' => ['events.html', 'events-daily.html', 'events-weekly.html', 'group-events.html'],
            'target_views' => ['resources/views/cups/index.blade.php', 'resources/views/cups/show.blade.php', 'resources/views/cups/create.blade.php', 'resources/views/cups/edit.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Events dienen als visuelle Basis, Cup-Scoring bleibt hnt.rocks-spezifisch.',
        ],
        [
            'area' => 'Referrals / Gewinnspiele',
            'route' => '/referrals',
            'template_files' => ['quests.html', 'overview.html'],
            'target_views' => ['resources/views/referrals/index.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Chancen, Referral-Fortschritt und Aktionen über Quest-/Progress-Pattern darstellen.',
        ],
        [
            'area' => 'Level / Badges / Quests',
            'route' => '/gamification',
            'template_files' => ['badges.html', 'quests.html', 'profile-badges.html'],
            'target_views' => ['resources/views/gamification/index.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Badge Cards, Progress und Quest Cards möglichst nah an Vikinger übernehmen.',
        ],
        [
            'area' => 'Account / Einstellungen',
            'route' => '/account, /settings/*',
            'template_files' => ['hub-account-info.html', 'hub-account-password.html', 'hub-account-settings.html', 'hub-profile-info.html', 'hub-profile-social.html'],
            'target_views' => ['resources/views/account/index.blade.php', 'resources/views/settings/privacy/edit.blade.php', 'resources/views/settings/security/index.blade.php'],
            'status' => 'funktional vorhanden, Design offen',
            'notes' => 'Account Hub als strukturelle Referenz nutzen.',
        ],
        [
            'area' => 'Admin / Moderation',
            'route' => '/admin',
            'template_files' => ['overview.html'],
            'target_views' => ['resources/views/admin/index.blade.php', 'resources/views/admin/users/index.blade.php', 'resources/views/admin/reports/index.blade.php', 'resources/views/admin/content/index.blade.php'],
            'status' => 'funktional vorhanden, Design später zweitrangig',
            'notes' => 'Admin muss bedienbar und stabil sein; 1:1 Frontend-Optik ist hier nicht zwingend.',
        ],
    ],
    'excluded_templates' => [
        'marketplace.html',
        'marketplace-category.html',
        'marketplace-product.html',
        'marketplace-cart.html',
        'marketplace-checkout.html',
        'profile-store.html',
        'hub-store-account.html',
        'hub-store-downloads.html',
        'hub-store-items.html',
        'hub-store-statement.html',
    ],
    'asset_strategy' => [
        'current' => 'Phase 22 importiert keine Marketplace-Funktion und lädt die offizielle Vikinger-CSS noch nicht global, damit bestehende Module nicht unkontrolliert brechen.',
        'next' => 'Phase 23 baut die Shell gezielt mit Vikinger-Klassen auf. Erst dann wird entschieden, welche offiziellen CSS/JS-Dateien global geladen werden.',
    ],
];
