#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CSS_DIR="$ROOT/public/assets/vikinger/css"
FONT_DIR="$ROOT/public/assets/vikinger/fonts"
GOOGLE_FONT_CSS="$CSS_DIR/hnt-local-fonts.css"
GOOGLE_FONT_DIR="$FONT_DIR/google"
PHOSPHOR_DIR="$FONT_DIR/phosphor/regular"

mkdir -p "$CSS_DIR" "$GOOGLE_FONT_DIR" "$PHOSPHOR_DIR"

if command -v curl >/dev/null 2>&1; then
  fetch() {
    local url="$1"
    local target="$2"
    curl -fsSL --retry 3 --connect-timeout 20 -A "Mozilla/5.0" "$url" -o "$target"
  }
elif command -v wget >/dev/null 2>&1; then
  fetch() {
    local url="$1"
    local target="$2"
    wget -q --tries=3 --timeout=20 --user-agent="Mozilla/5.0" -O "$target" "$url"
  }
else
  echo "ERROR: curl oder wget wird benötigt." >&2
  exit 1
fi

TMP_GOOGLE_CSS="$(mktemp)"
TMP_LOCAL_CSS="$(mktemp)"
cleanup() {
  rm -f "$TMP_GOOGLE_CSS" "$TMP_LOCAL_CSS"
}
trap cleanup EXIT

GOOGLE_CSS_URL="https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&family=Titillium+Web:wght@400;900&display=swap"
fetch "$GOOGLE_CSS_URL" "$TMP_GOOGLE_CSS"
cp "$TMP_GOOGLE_CSS" "$TMP_LOCAL_CSS"

# Google Fonts CSS enthält fonts.gstatic.com-URLs. Diese werden einmalig geladen
# und in der erzeugten CSS auf lokale /assets/vikinger/fonts/google/... Pfade umgeschrieben.
FONT_URLS="$(grep -oE 'https://fonts\.gstatic\.com/[^)"'"'"' ]+' "$TMP_GOOGLE_CSS" | sort -u || true)"

if [ -z "$FONT_URLS" ]; then
  echo "ERROR: Keine Google-Font-Dateien in der geladenen CSS gefunden." >&2
  exit 1
fi

while IFS= read -r font_url; do
  [ -z "$font_url" ] && continue
  file_name="$(basename "${font_url%%\?*}")"
  target="$GOOGLE_FONT_DIR/$file_name"
  fetch "$font_url" "$target"
  perl -0pi -e "s#\Q$font_url\E#/assets/vikinger/fonts/google/$file_name#g" "$TMP_LOCAL_CSS"
done <<< "$FONT_URLS"

{
  echo "/* Local Rajdhani + Titillium Web fonts for hnt.rocks. Generated by scripts/install-local-web-assets.sh. */"
  cat "$TMP_LOCAL_CSS"
} > "$GOOGLE_FONT_CSS"

PHOSPHOR_BASE="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.2/src/regular"
fetch "$PHOSPHOR_BASE/style.css" "$PHOSPHOR_DIR/style.css"
fetch "$PHOSPHOR_BASE/Phosphor.woff2" "$PHOSPHOR_DIR/Phosphor.woff2"
fetch "$PHOSPHOR_BASE/Phosphor.woff" "$PHOSPHOR_DIR/Phosphor.woff"
fetch "$PHOSPHOR_BASE/Phosphor.ttf" "$PHOSPHOR_DIR/Phosphor.ttf"
fetch "$PHOSPHOR_BASE/Phosphor.svg" "$PHOSPHOR_DIR/Phosphor.svg"

if grep -RInE 'fonts\.googleapis\.com|fonts\.gstatic\.com|cdn\.jsdelivr\.net/npm/@phosphor-icons/web' \
  "$ROOT/resources/views/partials/head.blade.php" \
  "$ROOT/resources/views/partials/vikinger/head.blade.php" \
  "$ROOT/public/assets/vikinger/css/styles.min.css" \
  "$ROOT/public/assets/vikinger/css/hnt-local-fonts.css" \
  "$ROOT/public/assets/vikinger/fonts/phosphor/regular/style.css" >/dev/null 2>&1; then
  echo "WARNING: Es wurden noch externe Font/Icon-Referenzen in Laufzeitdateien gefunden:" >&2
  grep -RInE 'fonts\.googleapis\.com|fonts\.gstatic\.com|cdn\.jsdelivr\.net/npm/@phosphor-icons/web' \
    "$ROOT/resources/views/partials/head.blade.php" \
    "$ROOT/resources/views/partials/vikinger/head.blade.php" \
    "$ROOT/public/assets/vikinger/css/styles.min.css" \
    "$ROOT/public/assets/vikinger/css/hnt-local-fonts.css" \
    "$ROOT/public/assets/vikinger/fonts/phosphor/regular/style.css" >&2 || true
  exit 1
fi

echo "OK: Lokale Fonts und Phosphor Icons wurden installiert."
echo "CSS: $GOOGLE_FONT_CSS"
echo "Phosphor: $PHOSPHOR_DIR"
